- name: Install go
  snap:
    name: go
    classic: yes
    state: present

- name: Copy ping_exporter source
  template:
    src: ping_exporter.go
    dest: /opt/ping_exporter.go

- name: Get go dependencies
  shell: go get github.com/gorilla/mux github.com/sparrc/go-ping

- name: Build ping_exporter
  shell: go build -o /opt/ping_exporter /opt/ping_exporter.go

- name: Install ping_exporter
  copy:
    src: /opt/ping_exporter
    dest: /usr/local/bin/ping_exporter
    owner: root
    mode: '0755'
    remote_src: yes

- name: Let unprivileged users do ping
  sysctl:
    name: net.ipv4.ping_group_range
    value: '0   2147483647'
    reload: yes

- name: Create unprivileged ping_exporter user
  user:
      name: ping_exporter
      create_home: no
      password: "*"
      shell: /usr/sbin/nologin
      system: yes
      state: present

- name: Install ping_exporter systemd service
  template:
    src: ping_exporter.service.j2
    dest: /etc/systemd/system/ping_exporter.service

- name: Start and enable ping_exporter
  systemd:
    name: ping_exporter
    daemon_reload: yes
    state: started
    enabled: yes

- name: Reload ping_exporter
  systemd:
    name: ping_exporter
    state: reloaded
    enabled: yes
