- name: Get timestamp
  shell: date +%s
  register: ts

- name: Apply db.foo
  template:
    src: templates/db.foo.j2
    dest: /etc/bind/db.foo

- name: Apply db.foo.ptr
  template:
    src: templates/db.foo.ptr.j2
    dest: /etc/bind/db.foo.ptr

- name: Reload bind database
  shell: rndc reload

- name: Reload bind configuration
  service:
    name: bind9
    state: reloaded
