- name: Fetch Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ pm_ver }}/prometheus-{{ pm_ver }}.linux-amd64.tar.gz
    dest: /opt/prometheus-{{ pm_ver }}.linux-amd64.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /opt/prometheus-{{ pm_ver }}.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes

- name: Install Prometheus
  copy:
    src: /opt/prometheus-{{ pm_ver }}.linux-amd64
    dest: /usr/local
    mode: '0755'
    remote_src: yes

- name: Install Prometheus config
  template:
    src: prometheus.yaml.j2
    dest: /usr/local/prometheus-{{ pm_ver }}.linux-amd64//prometheus.yaml

- name: Create unprivileged prometheus user
  user:
      name: prometheus
      create_home: no
      password: "*"
      shell: /usr/sbin/nologin
      system: yes
      state: present

- name: Create prometheus sotrage dir
  file:
    path: "/var/prometheus/data/"
    state: directory
    owner: prometheus
    group: prometheus

- name: Install Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start prometheus
  service:
    name: prometheus
    daemon_reload: yes
    state: started
    enabled: yes

- name: Reload prometheus
  systemd:
    name: prometheus
    state: reloaded
    enabled: yes
