- name: Stop and disable systemd-resolved
  systemd:    
    name: systemd-resolved
    enabled: no
    state: stopped

- name: resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
