---
- name: Setup BIND dns server
  hosts: dns
  remote_user: savva
  become: yes
  tasks:
  - name: Wait for any possibly running unattended upgrade to finish
    become: yes
    raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

  - name: Install BIND9 dns server
    become: yes
    apt:
      name: bind9
      update_cache: yes
      state: latest

  - name: Apply named.conf.options
    template:
      src: templates/named.conf.options.j2
      dest: /etc/bind/named.conf.options
      validate: 'named-checkconf %s'
    notify:
      - Reload bind configuration

  - name: Apply named.conf.local
    template:
      src: templates/named.conf.local.j2
      dest: /etc/bind/named.conf.local
      validate: 'named-checkconf %s'
    notify:
      - Reload bind configuration

  - name: Write db.foo hash
    copy:
      content: '{{ foo_records | hash }}'
      dest: /etc/bind/db.foo.hash
    when: dns_role == "master"
    notify:
      - Get timestamp
      - Apply db.foo
      - Reload bind database

  - name: Write db.foo.ptr hash
    copy:
      content: '{{ foo_ptr_records | hash }}'
      dest: /etc/bind/db.foo.ptr.hash
    when: dns_role == "master"
    notify:
      - Get timestamp
      - Apply db.foo.ptr
      - Reload bind database

  handlers:
  - name: Get timestamp
    shell: date +%s
    register: ts

  - name: Apply db.foo
    template:
      src: templates/db.foo.j2
      dest: /etc/bind/db.foo

  - name: Apply db.foo.ptr
    template:
      src: templates/db.foo.ptr.j2
      dest: /etc/bind/db.foo.ptr

  - name: Reload bind database
    shell: rndc reload

  - name: Reload bind configuration
    service:
      name: bind9
      state: reloaded
