---
- name: First play
  hosts: ubuntu-it-infra
  remote_user: savva
  tasks:
  - name: Run ping
    ping:

  - name: Install Savva's ssh key
    authorized_key:
      user: savva
      key: https://github.com/savva0.keys

  - name: process list
    command: ps a
    register: output

  - name: debug
    debug:
      var: output.stdout_lines

  - name: Update sudoers
    become: yes
    copy:
      mode: 0440
      dest: /etc/sudoers.d/sudoers
      content: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"

  - name: Create new group teachers
    become: yes
    group:
      name: sysadmins

  - name: Add user accounts for romankuchin
    become: yes
    user:
      name: romankuchin
      password: '!'
      groups: sysadmins

  - name: Install romankuchin's ssh key
    become: yes
    authorized_key:
      user: romankuchin
      key: https://github.com/romankuchin.keys
      
  - name: Add user accounts for hudolejev
    become: yes
    user:
      name: hudolejev
      password: '!'
      groups: sysadmins

  - name: Install hudolejev's ssh key
    become: yes
    authorized_key:
      user: hudolejev
      key: https://github.com/hudolejev.keys
