---
- name: Setup webserver
  hosts: ubuntu-it-infra
  remote_user: savva
  tasks:
  - name: Run ping
    ping:

  - name: Install Savva's ssh key
    authorized_key:
      user: savva
      key: https://github.com/savva0.keys

  - name: Update sudoers
    become: yes
    copy:
      mode: 0440
      dest: /etc/sudoers.d/sudoers
      content: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"

