- name: Fetch node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ ne_ver }}/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz
    dest: /opt/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz

- name: Extract node_exporter
  unarchive:
    src: /opt/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes

- name: Install node_exporter
  copy:
    src: /opt/node_exporter-{{ ne_ver }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes

- name: Create unprivileged node_exporter user
  user:
      name: node_exporter
      create_home: no
      password: "*"
      shell: /usr/sbin/nologin
      system: yes
      state: present

- name: Install node_exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter
  service:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes

- name: Reload node_exporter
  systemd:
    name: node_exporter
    state: reloaded
    enabled: yes
